### ISSUE TITLE
Link game icon with GUI on Linux

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#202]
**Edit:** Icon embedded for Windows has already been achieved for 0.5.0, what's left to do (or decide not to do if it's too complex) is to get the icon shown by Linux window managers in the title bar and task bar.

On Linux at least, the OD icon is not linked with the GUI, so the game window appears with the default Xorg icon (both in the taskbar and in the title bar).

A prerequisite to fixing this might be to design a nice-looking low-res icon (it should look good in 16x16 and 32x32, for higher resolutions the current icon is just fine) based on the current OD logo.

**Comment by Bertram25** [comment]
I guess I'm the icon guy ;) But isn't the default icon size requested by XDG specs 48x48?

I would concentrate on that one and that one alone. WDYT?

**Comment by akien-mga** [comment]
What I mean is that the current icon ( https://github.com/OpenDungeons/OpenDungeons-media-source/blob/master/Logo/OpenDungeons-Logo.svg ) looks quite good already when resized to 48x48, see:
![opendungeons](https://cloud.githubusercontent.com/assets/4701338/4447568/bc0a8b9c-480b-11e4-84df-476cfde64828.png)

But with smaller resolutions, you can't really see the details of demonic "D", and it becomes hard to read.
The XDG specs require at least a 48x48 icon, but you can provide more in the hicolor theme, with the help of the various subdirectories in /usr/share/icons/hicolor, e.g. with:
/usr/share/icons/hicolor/16x16/apps/opendungeons.png
/usr/share/icons/hicolor/48x48/apps/opendungeons.png

If your desktop environment needs an icon small or equal to 16x16, it will use the one in /usr/share/icons/hicolor/16x16/apps/opendungeons.png and scale it down if need be.
If it needs something between 16x16 and 48x48, it will use /usr/share/icons/hicolor/48x48/apps/opendungeons.png
This way we can provide a different icon in those two paths.

**Comment by Bertram25** [comment]
Ok, now I see the point completely. I'll work tomorrow on the 32x32 and 16x16 versions if nobody else does it. :)

**Comment by Bertram25** [comment]
What do you think of those?
![od-16x16](https://cloud.githubusercontent.com/assets/765917/4809166/12c712da-5ea9-11e4-81fd-614c0ce51c35.png)
![od-32x32](https://cloud.githubusercontent.com/assets/765917/4809168/168b5962-5ea9-11e4-8d31-86a177892423.png)
I've reworked the outline for 32x32 one and simplified the pattern for the 16x16 one.

**Comment by akien-mga** [comment]
It's not 100% perfect, but it's good enough for now IMO. I'm looking forward to seeing it in the taskbar :-)

**Comment by Bertram25** [comment]
@akien-mga It's true I'm still not happy with the outline of 32x32 version. I'll improve it when seeing it live ;)
In the meanwhile, feel free to point out whatever feels bad.

**Comment by akien-mga** [comment]
> In the meanwhile, feel free to point out whatever feels bad.

I like the 16x16 icon, you edited it well. As you say the outline of the 32x32 is not perfect yet, maybe some further simplification of the icon would be needed. I can have a go at it, but as you say, the drive will probably come when we see it live :-)

**Comment by Bertram25** [comment]
I'll leave the 32x32 for now as the one shipped actually looks better IMHO.

**Comment by Bertram25** [comment]
@akien-mga I've not yet looked at the opendungeons icon handling on linux but this should work on windows:
http://www.ogre3d.org/tikiwiki/tiki-index.php?page=Custom+Icon+and+Cursor

I also suppose a windows res file has to be created for windows. I'll handle it.

**Comment by Bertram25** [comment]
For self-reference:
http://www.ogre3d.org/forums/viewtopic.php?f=3&t=17948&start=25
http://www.winprog.org/tutorial/menus.html
http://stackoverflow.com/questions/13187453/load-window-icon-dynamically

**Comment by akien-mga** [comment]
> I've not yet looked at the opendungeons icon handling on linux

As I said in 44f1f09, there is no way to embed an icon in the executable on Linux. But we don't really need that either. The .desktop file handles the menu icon for the game, so what's left is the actual game window icon that will be displayed by the window manager in the title bar (if running in windowed mode) and in the taskbar (at least for desktop environments that do have this stuff like KDE, I don't know about GNOME :-).

I think we should search for a built-in function provided by the library we use to spawn the window. Is it handled by Ogre, SFML, X11 or something else?

**Comment by akien-mga** [comment]
I've had a look at how Stunt Rally manages that, and it seems they convert an Ogre image to a SDL surface before using a SDL function to set the actual icon: https://github.com/stuntrally/stuntrally/blob/master/source/sdl4ogre/sdlwindowhelper.cpp

**Comment by oyvindln** [comment]
The window creation is handled by Ogre.

**Comment by Bertram25** [comment]
> The window creation is handled by Ogre.

Still, I'd look at SDL source code to see how they do it.

**Comment by Bertram25** [comment]
I'll have a look at SDL source code to know how they do it. :)

**Comment by Bertram25** [comment]
Ladies and gentlemen, please welcome X11_SetWindowIcon():
https://hg.libsdl.org/SDL/file/d0865e9f674a/src/video/x11/SDL_x11window.c#l724

I'll have a look at whether we can use this.

**Comment by Bertram25** [comment]
So my anwser will be meh: XD

Basically, I'd need to dissect The Ogre window creation to get back the Display and Window handle.
Then, use an Ogre::Image to load the icon in the right format and use its data to load it.

```
XChangeProperty(display, w, property, type, format, mode, data, nelements)
      Display *display;
      Window w;
      Atom property, type;
      int format;
      int mode;
      unsigned char *data;
      int nelements;
```

I'll be honest, I don't feel like doing this, at least atm.
@akien-mga Will you kill me if I say Won't fix for this one?

**Comment by Bertram25** [comment]
@akien-mga gave me hope as he found some interesting code in Ogre about setting up icons. Namely:
https://bitbucket.org/sinbad/ogre/src/2271eda512b5afc825797e748066a3c21e8c03c6/RenderSystems/GL/include/GLX/OgreGLXGLSupport.h?at=default#cl-126
https://bitbucket.org/sinbad/ogre/src/2271eda512b5afc825797e748066a3c21e8c03c6/RenderSystems/GL/src/GLX/OgreGLXWindow.cpp?at=default#cl-392

I'll have a look at that but it might take a few days. For the record, feel free to release if it's ready in the meanwhile.

**Comment by akien-mga** [comment]
The Windows part of this bug is fixed, I edited the first post and move the Linux part of the issue to 0.6.0.

**Comment by Bertram25** [comment]
For the record: In ODApplication.cpp:

```
#include <X11/Xlib.h>
...
#elif OGRE_PLATFORM == OGRE_PLATFORM_LINUX
    Window xWindow;
    renderWindow->getCustomAttribute("WINDOW", static_cast<Window*>(&xWindow));
    Display* xDisplay = nullptr;
    renderWindow->getCustomAttribute("DISPLAY", static_cast<Display*>(xDisplay));
    Atom net_wm_icon = XInternAtom(xDisplay, "_NET_WM_ICON", False);
    Atom cardinal = XInternAtom(xDisplay, "CARDINAL", False);
    XChangeProperty(xDisplay, xWindow, net_wm_icon, cardinal,
                                32, PropModeReplace, /*(const unsigned char *)*/ 0,
                                0);
#endif 
```

Ah, and add -lX11 to the linker flags.

The next step is to get a const unsigned char\* valid buffer used as an icon. Phew... Still not actually sure it will work, though. :/

**Comment by Bertram25** [comment]
Arf, can't get it to work even when passing a valid buffer + its size.
If someone wants to take it, I'll gladly let you. :) I'll move onto something else.

**Comment by Bertram25** [comment]
I've opened a topic on Ogre about this one:
http://www.ogre3d.org/forums/viewtopic.php?f=2&t=83337

But I'm still stuck and I won't hack Ogre further for now. Let's see how it turns. ;)
