### ISSUE TITLE
When a player disconnects, the log gets full of failing assert

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#643]
In ODServer.cpp:155 due to the fact the player has no more client. This assert is still usefull to know what happens ingame. It should probably be replaced by a log that is displayed only once per player

**Comment by hwoarangmy** [comment]
Fixed in #653

**Comment by Bertram25** [comment]
Isn't the reverse still true? I mean I think the clients still get spammed when the server disconnects from what I could see. I'll retest though.
